---
- name: Manage Nessus Agent
  hosts: all
  become: yes
  tasks:
    - name: Stop Nessus Agent service
      systemd:
        name: nessusagent
        state: stopped

    - name: Set update_hostname to 'yes' for Nessus Agent
      command: /opt/nessus_agent/sbin/nessuscli fix --set update_hostname=yes

    - name: Unlink Nessus agent and remove associated files
      shell: |
        /opt/nessus_agent/sbin/nessuscli agent unlink
        rm -rf /etc/tenable_tag /etc/machine_id
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Link Nessus agent to Tenable Cloud
      command: >
        /opt/nessus_agent/sbin/nessuscli agent link --host=cloud.tenable.com --port=443
        --key={{ nessus_cloud_key }}
        --groups={{ nessus_groups }}

    - name: Start Nessus Agent service
      systemd:
        name: nessusagent
        state: started

    - name: Check Nessus Agent status
      command: /opt/nessus_agent/sbin/nessuscli agent status
      register: nessus_status

    - name: Display Nessus Agent status
      debug:
        msg: "Nessus Agent status: {{ nessus_status.stdout }}"

    - name: Check systemd status of Nessus Agent service
      systemd:
        name: nessusagent
        state: started
      register: systemd_status

    - name: Display systemd status of Nessus Agent service
      debug:
        msg: "Nessus Agent systemd status: {{ systemd_status.status }}"
