---
- name: Install Nessus Agent on Multiple Servers
  hosts: all  # Targeting VPN_EU group here
  become: yes
  tasks:
    - name: Remove old Nessus Agent
      apt:
        name: nessus-agent
        state: absent
      when: ansible_facts['pkg_mgr'] == 'apt'

    - name: Download Nessus Agent package
      get_url:
        url: "https://edcast-devops-us-prd.s3.us-east-1.amazonaws.com/NessusAgent-10.8.2-ubuntu1804_aarch64.deb"
        dest: "/tmp/NessusAgent-10.8.2-ubuntu1604_amd64.deb"
        mode: '0644'

    - name: Install Nessus Agent
      shell: |
        sudo dpkg -i /tmp/NessusAgent-10.8.2-ubuntu1604_amd64.deb || sudo apt-get -f install -y
      args:
        executable: /bin/bash

    - name: Restart Nessus Agent service
      systemd:
        name: nessusagent
        state: restarted

    - name: Verify Nessus Agent installation
      command: /opt/nessus_agent/sbin/nessuscli --version
      register: nessus_version
      changed_when: false

    - name: Show installed Nessus Agent version
      debug:
        msg: "Installed Nessus Agent version: {{ nessus_version.stdout }}"
